### ISSUE TITLE
Displaying all map outlines

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#27]
When in the yellow page, it's not obvious that there are multiple maps within the main outlines. Currently, you see the total area mapped and then when mousing, view the individual maps covering that point. How could we convey the intermediate view—a birds-eye view of all the maps? Might be a good learning moment for some users, as it is a visual parallel to the "WHAT MAPS ARE HERE?" explanation in the building inspector [About page](http://buildinginspector.nypl.org/about).

**Comment by bertspaan** [comment]
No, too many maps!
