### ISSUE TITLE
Include contact information for patrons needing more info.

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#50]
Check with relevant divisions about best contact for patrons needing more information, help, or want to visit the collections in person. Include this information in the About page and in the homepage (for homepage could be something available to screen readers and not visibly rendered.)

**Comment by wlla** [comment]
This information will be covered by the policy being included in the About page.

**Comment by hadro** [comment]
Copy pushed, pending final tweaks

**Comment by wlla** [comment]
Included multiple email contacts and phone number.
