### ISSUE TITLE
IE Testing

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#55]
Test updated site on on IE.

**Comment by wlla** [comment]
Used site on IE 11 with Windows 7. Some notes:
* Selecting "previous" and "next" buttons don't work (though keyboard shortcut of "shift + ]" did work)
* Focus not visible when tabbing through pages 

* Works okay at 200% magnification

**Comment by bertspaan** [comment]
@wlla Did you test latest version? Can I close this issue?

**Comment by wlla** [comment]
Yes; focus is now visible.
