### ISSUE TITLE
About page headers

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#56]
Headers sequence in About page needs to be reviewed. Order seems correct but 2 levels skipped (ie, moves from h2 to h4).

**Comment by bertspaan** [comment]
All levels are there: _Maps by Decade_ in header is `<h1>`, _The New York Public Library_ is `<h2>`, _Space/Time Directory_ is `<h3>`, and the first heading in About page, _About Maps by Decade_, is `<h4>`:

![image](https://cloud.githubusercontent.com/assets/1194896/22762879/aab2570e-ee2f-11e6-933e-40446fce25d6.png)

**Comment by wlla** [comment]
As long as these headings are listed in the correct sequence in the markup we can close the ticket.
