### ISSUE TITLE
[List Page] Redundant title text

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#67]
50 X Redundant title text - for each item the body text and title text is identical.  The title attribute value should be used to provide advisory information.

**Comment by bertspaan** [comment]
This is intentional - I'm using identical title text because we truncate long titles with ellipsis.

**Comment by bertspaan** [comment]
We could use [`aria-hidden`](http://www.456bereastreet.com/archive/201205/hiding_visible_content_from_screen_readers_with_aria-hidden/) maybe? And put actual content in subelement?
