### ISSUE TITLE
Re-assess Kindle Fire display issues

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#69]
Kindle Fire display issues were flagged in the qa testing. Re-test with real device.

https://docs.google.com/document/d/1PsIgXsQIwpqSEEAy5oNXWqRZOm9GtLLLNlP2_rEtkYk/edit?ts=5888bfb6#

**Comment by bertspaan** [comment]
Nobody uses a Kindle Fire.

**Comment by wlla** [comment]
Reviewed with real device (Kindle Fire / Silk browser) and didn't find the display errors flagged in qa doc. Think the display error was due to emulator or related to some other ticket that was closed.
