### ISSUE TITLE
Assess and make plan for VoiceOver Issues

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#70]
* [x] Map page - “heading level 2 1850-1859” - entire group is not described
* [x] Map detail page - I can’t interact with map elements on this page. (can’t move with cursor)
* [x] List page - check boxes at top of page read as “1850s checkbox”, etc., without any description of the section or what they do.
* [x] List page - title search.  Voice over can’t read the number of results found after search.
* [x] No description for pagination links for search results

Flagged in QA. Make plan.

Also flagged:
On Homepage, if you tab through the list of decades with voiceover on, each one just says "group". If you wrap each on in a link, it should use the heading. Future enhancement might be to consider aria-labelledby and a hidden element to spell out the dates (i.e. "Eighteen sixty to eighteen to sixty nine") since otherwise it just reads out the digits.

**Comment by wlla** [comment]
Test on an ipad mini and was able to use VoiceOver to read number of results found so I'm not sure what's going on with the penultimate point.

Consider similar fix as this: http://www.a11ymatters.com/pattern/pagination/ for pagination links issue.

**Comment by bertspaan** [comment]
@wlla : I've used http://www.a11ymatters.com/pattern/pagination/ and created my own pagination control instead of using [react-paginate](https://github.com/AdeleD/react-paginate). This should solve some of the issues.

**Comment by wlla** [comment]
@mgiraldo and I tested the most recent version yesterday and did not encounter these bugs. Some of them may have been the result of navigating only with the Tab key.
