### ISSUE TITLE
Keyboard trap

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#87]
Map page: reload the page and hit tab 7 times. The focus is trapped on the NYPL logo

https://docs.google.com/a/nypl.org/document/d/1xHhy6qQfZhWq-KktV__cWSfCnPQtTe0fhapS_Ka2HWs/edit?disco=AAAAA8gQDss

**Comment by bertspaan** [comment]
@wlla : the main map page with the small maps? I can't reproduce this. Which browser?

**Comment by wlla** [comment]
@seanredmond additional details needed on reported bug; see earlier comment.
