### ISSUE TITLE
Missing form label in list filter

### ISSUE THREAD

**Issue by seanredmond** [nypl-spacetime/maps-by-decade#95]
There is a missing label/element relationship on the filter by title input:

    <fieldset class="GWeic">
        <legend>Filter by title:</legend>
        <div class="hhpmBF">
            <input type="text" name="title" value="" id="filter-title" autocomplete="off" placeholder="e.g. &quot;greenpoint&quot;">
        </div>
    </fieldset>

The `label` just needs a `for`?

**Comment by bertspaan** [comment]
There is no label...

**Comment by seanredmond** [comment]
Right. Since there is only one field it probably shouldn't be a `<fieldset>`, but just a `<label>` and `<input`> (in a `<div>` or something if you need that to hang CSS on)
